Fixed some issues and removed display errors
rufreakde/hide-amazon-prices pull request #1
Opened 2022-03-17 21:49 UTC by Brokkolii

accidentally formatted the whole files

2022-03-22 10:09 UTC, rufreakde commented
Hi @Brokkolii ,
I will review the PR as soon as I have time for it. Will be today or tomorrow evening.

2022-03-22 19:38 UTC, rufreakde requested changes
prettier formatting (thats okay I switched to prettier as well)
Change of the css rule LGTM except I would like to keep the blurr effect as optional.

See the improvement I suggest.

We can merge afterwards maybe we can update the readme as well then. :)

2022-03-22 19:38 UTC, rufreakde commented on content.js
>  `;
```suggestion
const blurr = useBlurr ? "text-shadow: rgba(0, 0, 0, 0.8) -10px 0px 30px !important;" : "";
const cssRuleElement = `span[class*="price"],
span[class="tmm-olp-links"] *
{
    color: transparent !important;
    ${blurr}
    user-select: none;
  }
`;
```

I like this suggestion but lets keep the blur effect as an optional and add it into the readme.

2022-03-22 22:36 UTC, Brokkolii commented
Yeah, you are right with the blur! i was just playing around :)

2022-03-23 07:22 UTC, rufreakde approved these changes
lgtm

2022-03-23 07:22 UTC, rufreakde commented
merging

2022-03-23 07:22 UTC, merged